//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Cliente
{
    public int IdCliente { get; set; }
    public int CedulaCli { get; set; }
    public string NomCli { get; set; }
    public string DirCli { get; set; }
    public string telCli { get; set; }
    public string PassCli { get; set; }

    public Cliente(int idCliente, int cedulaCli, string nomCli, string dirCli, string telCli, string passCli)
    {
        IdCliente = idCliente;
        CedulaCli = cedulaCli;
        NomCli = nomCli;
        DirCli = dirCli;
        this.telCli = telCli;
        PassCli = passCli;
    }

    public Cliente()
    {
    }
}
