//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class Cuota
{
    public int IDCu { get; set; }
    public decimal ImporteCu { get; set; }
    public long NumeroTCU { get; set; }

    public Cuota(int iDCu, decimal importeCu, long numeroTCU)
    {
        IDCu = iDCu;
        ImporteCu = importeCu;
        NumeroTCU = numeroTCU;
    }

    public Cuota()
    {
    }
}