//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;


public partial class FacturaCompra
{
    public int IdFC { get; set; }
    public string NumeroFC { get; set; }
    public string ProvFC { get; set; }
    public System.DateTime FechaFC { get; set; }
    public Nullable<decimal> ImpuestosFC { get; set; }
    public Nullable<decimal> SubtotalFC { get; set; }
    public Nullable<decimal> TotalFC { get; set; }
    public List<LineaFacturaCompra> Listalineas { get; set; }

    public FacturaCompra(int idFC, string numeroFC, string provFC, DateTime fechaFC, decimal? impuestosFC, decimal? subtotalFC, decimal? totalFC, List<LineaFacturaCompra> listalineas)
    {
        IdFC = idFC;
        NumeroFC = numeroFC;
        ProvFC = provFC;
        FechaFC = fechaFC;
        ImpuestosFC = impuestosFC;
        SubtotalFC = subtotalFC;
        TotalFC = totalFC;
        Listalineas = listalineas;
    }

    public FacturaCompra()
    {
    }
}
