//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LineaVenta
{
    public int IdLV { get; set; }
    public int ProductoLV { get; set; }
    public int IdV { get; set; }
    public int CantidadLV { get; set; }
    public decimal ImporteLV { get; set; }
    public decimal PrecioprodV { get; set; }
    public decimal Importeob { get; set; }
    public virtual Producto Producto { get; set; }
    public virtual Venta Venta { get; set; }
    public int Cantidad { get; set; }

    public LineaVenta(int idLV, int productoLV, int idV, int cantidadLV, decimal importeLV)
    {
        IdLV = idLV;
        ProductoLV = productoLV;
        IdV = idV;
        CantidadLV = cantidadLV;
        ImporteLV = importeLV;
    }

    public LineaVenta()
    {
    }
}
