//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LineaFacturaCompra
{
    public int IdLFC { get; set; }
    public int ProductoLFC { get; set; }
    public int CantidadLFC { get; set; }
    public decimal ImporteLFC { get; set; }
    public int IdFacturaCompra { get; set; }

    public virtual Producto Producto { get; set; }

    public LineaFacturaCompra(int idLFC, int productoLFC, int cantidadLFC, decimal importeLFC, int idFacturaCompra)
    {
        IdLFC = idLFC;
        ProductoLFC = productoLFC;
        CantidadLFC = cantidadLFC;
        ImporteLFC = importeLFC;
        IdFacturaCompra = idFacturaCompra;
    }

    public LineaFacturaCompra()
    {
    }
}