//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class LineaCompra
{

    public int IdLC { get; set; }
    public int ProductoLC { get; set; }

    public int IdC { get; set; }
    public int CantidadLC { get; set; }
    public decimal ImporteLC { get; set; }
    public decimal PrecioprodLC { get; set; }
    public virtual Compra Compra { get; set; }
    public virtual Producto Producto { get; set; }

    public LineaCompra(int idLC, int productoLC, int idC, int cantidadLC, decimal importeLC)
    {
        IdLC = idLC;
        ProductoLC = productoLC;
        IdC = idC;
        CantidadLC = cantidadLC;
        ImporteLC = importeLC;

    }

    public LineaCompra()
    {
    }
}
