//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Mensaje
{

    public int IdMensaje { get; set; }
    public string ComentarioMens { get; set; }
    public int Clicom { get; set; }
    public Nullable<long> Vendresp { get; set; }
    public string RespuestaMens { get; set; }
    public System.DateTime Fechaenvio { get; set; }
    public Nullable<System.DateTime> Fecharespuesta { get; set; }

    public Mensaje(int idMensaje, string comentarioMens, int clicom, long? vendresp, string respuestaMens, DateTime fechaenvio, DateTime? fecharespuesta)
    {
        IdMensaje = idMensaje;
        ComentarioMens = comentarioMens;
        Clicom = clicom;
        Vendresp = vendresp;
        RespuestaMens = respuestaMens;
        Fechaenvio = fechaenvio;
        Fecharespuesta = fecharespuesta;
    }

    public Mensaje()
    {
    }
}

