//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class PagoTarjeta
{

    public int IDPT { get; set; }
    public long NumeroT { get; set; }
    public int ClienteT { get; set; }
    public int CantidadCuT { get; set; }
    public decimal TotalT { get; set; }
    public List<Cuota> Listacuotas { get; set; }

    public PagoTarjeta(int iDPT, long numeroT, int clienteT, int cantidadCuT, decimal totalT, List<Cuota> listacuotas)
    {
        IDPT = iDPT;
        NumeroT = numeroT;
        ClienteT = clienteT;
        CantidadCuT = cantidadCuT;
        TotalT = totalT;
        Listacuotas = listacuotas;
    }

    public PagoTarjeta()
    {
    }
}
