//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ProductosOE
{
    public int IdProdOE { get; set; }
    public int POE { get; set; }
    public int IdOrdenE { get; set; }

    public virtual Producto Producto { get; set; }

    public ProductosOE(int idProdOE, int pOE, int idOrdenE)
    {
        IdProdOE = idProdOE;
        POE = pOE;
        IdOrdenE = idOrdenE;
    }

    public ProductosOE()
    {
    }
}
