//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Proveedor
{
    public int IdProveedor { get; set; }
    public string RutProv { get; set; }
    public string NomProve { get; set; }
    public string DirProve { get; set; }
    public string telProve { get; set; }
    public bool BajaProv { get; set; }

    public Proveedor(int idProveedor, string rutProv, string nomProve, string dirProve, string telProve,bool bajaprov)
    {
        IdProveedor = idProveedor;
        RutProv = rutProv;
        NomProve = nomProve;
        DirProve = dirProve;
        this.telProve = telProve;
        BajaProv = bajaprov;
    }

    public Proveedor()
    {
    }
}