//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Tecnico : Usuario
{
    public int IdTecnico { get; set; }
    public long cedulaTecnico { get; set; }
    public bool BajaTec { get; set; }
    public Tecnico(int idusu, long cedulaUsu, string nombreUsu, string claveUsu, decimal sueldo, DateTime fechaIngreso, bool bajausu)
      : base(idusu, cedulaUsu, nombreUsu, claveUsu, sueldo, fechaIngreso,  bajausu)
    {

    }

    public Tecnico() : base()
    { }
}

