//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Usuario
{
    public int Idusu { get; set; }
    public long CedulaUsu { get; set; }
    public string NombreUsu { get; set; }
    public string ClaveUsu { get; set; }
    public decimal Sueldo { get; set; }
    public System.DateTime FechaIngreso { get; set; }
    public bool BajaUsu { get; set; }
    public Usuario(int idusu, long cedulaUsu, string nombreUsu, string claveUsu, decimal sueldo, DateTime fechaIngreso,bool bajausu)
    {
        Idusu = idusu;
        CedulaUsu = cedulaUsu;
        NombreUsu = nombreUsu;
        ClaveUsu = claveUsu;
        Sueldo = sueldo;
        FechaIngreso = fechaIngreso;
        BajaUsu = bajausu;
    }
    public Usuario()
    { }
}
