//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Venta
{
    public int IdV { get; set; }
    public System.DateTime FechaV { get; set; }
    public System.DateTime VencimientoV { get; set; }
    public string MetodoPagoV { get; set; }
    public int? ClienteV { get; set; }
    public Nullable<long> TarjetaV { get; set; }
    public decimal ImpuestosV { get; set; }
    public decimal SubtotalV { get; set; }
    public decimal TotalV { get; set; }
    public string FormaEntregaV { get; set; }
    public string EstadoV { get; set; }
    public virtual OrdenEnvio OrdenEnvio { get; set; }
    public List<LineaVenta> LineaVenta { get; set; }

    public Venta(int idV, DateTime fechaV, DateTime vencimientoV, string metodoPago, int? clienteV, long? tarjetaV, decimal impuestosV, decimal subtotalV, decimal totalV, string formaEntregaV, string estadoV, List<LineaVenta> lineaVenta)
    {
        IdV = idV;
        FechaV = fechaV;
        VencimientoV = vencimientoV;
        MetodoPagoV = metodoPago;
        ClienteV = clienteV;
        TarjetaV = tarjetaV;
        ImpuestosV = impuestosV;
        SubtotalV = subtotalV;
        TotalV = totalV;
        FormaEntregaV = formaEntregaV;
        EstadoV = estadoV;
        LineaVenta = lineaVenta;
    }

    public Venta()
    {

    }
}
